#!/bin/bash

# Sæt hjem
hjem=$(pwd)

# Sæt hjælp og nulstil til første opgave
alias hjælp='glow $hjem/Terminal-træning/intro.md'
alias start='clear && cd $hjem/Terminal-træning && glow intro.md'

cd() {
    if [[ $@ == "piratskibet" ]]; then
        echo "Kaptajnen vil have du finder beskeden før du kommer ombord"
    elif [[ $@ == "pirathavn" ]]; then
	echo "Velkommen til pirathavnen, tjek omgivelserne med: cat pirathavn"
	pushd $@>/dev/null
    else
        command cd "$@"
    fi
}

alias opgave3='echo "# Sådan det køre....\n\n### virker det..?" >> næste_opgave.md | glow næste_opgave.md'
