#!/bin/bash

# Sæt hjem
hjem=$(pwd)

hjælp() {
    glow $hjem/Terminal-træning/intro.md
}

start() {
    clear
    cd $hjem/Terminal-træning
    glow intro.md
}

cd() {
    if [[ $@ == "piratskibet" ]] || [[ $@ == "piratskibet/" ]]; then
        echo "Kaptajnen vil have du finder beskeden før du kommer ombord"
    elif [[ $@ == "pirathavn" ]] || [[ $@ == "pirathavn/" ]]; then
	echo
	echo "Velkommen til pirathavnen, tjek omgivelserne med: cat pirathavn"
	echo
	pushd $@>/dev/null
    else
        command cd "$@"
    fi
}

alias opgave3='echo "# Sådan det køre....\n\n### virker det..?" >> næste_opgave.md | glow næste_opgave.md'
