#!/bin/bash

cooldown_period=33
current_time=$(date +%s)

if [ -f ".cooldown" ]; then
	if [[ $((current_time - cooldown_period)) -gt $(cat .cooldown) ]]; then
		rm .cooldown
		echo
		echo "Papegøjen spørger: tør du komme an igen?"
		echo
	else
		echo
		echo "Papegøjen kigger på dig og horisonten med foragt: du er ikke en værdig modstander!"
		echo
		exit 0
	fi
fi

player_life=10
parrot_life=10

player_insults=("Din fjerløse papegøje! Hvordan flyver du med de øjne?"
                "Du ser ud som om du har spist for mange dårlige skattekort!"
                "Hvorfor er dit ene øje stort som en skattekiste og det andet lille som en mønt?"
                "Du er så skeløjet, at du kunne se to skatte på én gang!"
)
parrot_insults=("Du er ikke mere end en skødehund for kaptajnen!"
                "Din pirat aspirant! Du kan ikke engang se en skat, hvis den stod lige foran dig!"
                "Hvorfor har du en krog i din hånd? Tror du, du kan narre mig med det?"
                "Dit hår er så rodet, at det ligner du har været i en orkan! Vent, det var nok bare din hat!")


echo
echo "Du går langs havnen og opdager pludselig en skeløjet papegøje, der sidder på en tønde."
echo "Papegøjen ser på dig og siger med en hæs stemme: 'Du er så værdiløs, at selv havmågerne nægter at stjæle dine kiks!'"
echo

while [ $player_life -gt 0 ] && [ $parrot_life -gt 0 ]; do
    echo ""
    echo "Dit liv: $player_life | Papegøjens liv: $parrot_life"
    echo "Hvad gør du?"
    echo "1. Fornærmer papegøjen."
    echo "2. Prøver at lokke papegøjen med en lækker kiks."
    echo
    read choice
    
    if [ $choice -eq 1 ]; then
        insult_index=$((RANDOM % ${#player_insults[@]}))
        insult=${player_insults[$insult_index]}
        echo "Du siger: '$insult'"
        
        parrot_life=$((parrot_life - (RANDOM % 4 + 1)))
        insult_index=$((RANDOM % ${#parrot_insults[@]}))
        insult=${parrot_insults[$insult_index]}
        echo "Papegøjen råber: '$insult'"
        player_life=$((player_life - (RANDOM % 3 + 1)))
    elif [ $choice -eq 2 ]; then
        echo "Du prøver at lokke papegøjen med en kiks, men den er ikke imponeret."
        echo "Papegøjen siger: 'Kiks er ikke nok til at narre mig, du pirat aspirant!'"
        player_life=$((player_life - (RANDOM % 7 + 1)))
    else
        echo "Ugyldigt valg. Prøv igen."
    fi
done

if [ $player_life -le 0 ]; then
    echo
    echo "Den skeløjede papegøje skriger: find en ligeværdig modstander!"
    echo "Du kigger slukøret på den prægtige og hoverende fugl!"
    echo
    echo $(date +%s)>.cooldown
else
    echo
    echo "Tillykke! Du har besejret den skeløjede papegøje! Papegøjen flyver op på toppen af skibsværftet, hvor du kan høre den sidder og knurrer!"
    echo
    mv papegøje .papegøje
    echo "Du kan nu hovere over papegøjen ved at lave en variabel 'pape':"
    echo
    echo "export pape=1"
    echo
    echo "Tjek frugten af dit hårde arbejde med:"
    echo 
    echo "echo \$pape"
    echo 
fi

exit 0


























































# Dette er et script som du skal køre. Ved du hvordan?
