#!/bin/bash
echo
echo "Det svage skær af lamperne afslører et nøje udskåret net af træværk og stål, der danner skroget af et piratskib under konstruktion. Skyggerne danser på væggene og afslører detaljer, der ellers gemmer sig i mørket. Du bemærker der er en masse kontakter som ikke er forbundet bag det halvfærdige piratskib."
echo
echo Brug chmod u+x [filnavn] til at forbinde kontakterne.
echo


































